spring:
  profiles:
    default: "dev"
  messages:
    basename: lang/messages
  application:
    name: user
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      # uri: mongodb://localhost:27017/userDB
  cloud:
    bootstrap:
      enabled: true
  graphql:
    graphiql:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}
          jwt-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
server:
  port: 5100
spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761}
      # defaultZone: http://localhost:8761
keycloak-client:
  server-url: http://172.31.211.174:8080
  realm: netflix