version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: netflixDB
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  user-service:
    build: ./user
    ports:
      - "5100:5100"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/userDB
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - mongo

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - user-service

volumes:
  mongodata:
